baseURL = 'http://users.ugent.be/~mvuijlst/'
defaultContentLanguage = 'nl'
title = 'Moose Dept.'
theme = 'moose'

buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true